# Generated by Django 5.2.15 on 2026-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('section', models.CharField(max_length=40)),
            ],
        ),
    ]
