services:
  - type: web
    name: student-material-hub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn firstdjangoproj.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        sync: false
